services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html:ro
      # 將 Docker socket 掛載到 /tmp/docker.sock，這是 nginx-proxy 使用的位置
      - /var/run/docker.sock:/tmp/docker.sock:ro

  acme-companion:
    image: nginxproxy/acme-companion:latest
    restart: always
    depends_on:
      - nginx-proxy
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - DEFAULT_EMAIL=${DEFAULT_EMAIL}
    volumes:
      - ./certs:/etc/nginx/certs:rw
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html:rw
      - ./acme:/etc/acme.sh
      # acme-companion 需讀取 Docker socket 的真實位置
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  default:
    name: nginx-proxy
