version: '3.8'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html:ro
      # 將 Docker socket 掛載到 /tmp/docker.sock，這是 nginx-proxy 使用的位置
      - /var/run/docker.sock:/tmp/docker.sock:ro

  acme-companion:
    image: nginxproxy/acme-companion:latest
    restart: always
    depends_on:
      - nginx-proxy
    environment:
      # 請修改為你的電子郵件，用於 Let's Encrypt 通知
      - ACME_EMAIL=you@example.com
      # 測試模式（staging）：在測試時取消註解下面一行以避免觸及 production rate limits
      - ACME_CA_URI=https://acme-staging-v02.api.letsencrypt.org/directory
    volumes:
      - ./certs:/etc/nginx/certs:rw
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html:rw
      - ./acme:/etc/acme.sh
      # acme-companion 需讀取 Docker socket 的真實位置
      - /var/run/docker.sock:/var/run/docker.sock:ro
    
